---
title: "Models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lme4)
library(broom.mixed)
```

Get data and put it in long form 
```{r}
pins::board_register_github(repo = "karinorman/biodivTS_data", branch = "master")

#get metadata
meta <- pins::pin_get("meta", board = "github") %>%
  select(study_id, realm, climate, habitat, protected_area, biome_map)

meta <- pins::pin_get("bt-traitfiltered", board = "github") %>%
  select(study_id, rarefyid, taxa) %>% distinct() %>%
  left_join(meta)

#get metric data
metrics <- pins::pin_get("rarefied-metrics", board = "github") %>%
  # pivot_longer(., cols = setdiff(everything(), one_of("rarefyID", "STUDY_ID", "SamplePool", "SampleN", "num_years", "duration", "startYear", "endYear", "YEAR", "cell", "rarefied", "type", "realm", "climate", "habitat", "biome_map", "taxa", "organisms", "cent_lat", "cent_long", "abundance_type", "BROAD_TYPE", "taxa_mod", "climate_mod")), names_to = "metric", values_to = "value") %>%
  rename_with(tolower, .cols = setdiff(everything(), one_of("rarefyID")))  %>%
  filter(!is.na(value)) %>%
  mutate(logvalue = log(value + 1)) %>% # create a column for log transformation that adds the absolute value integer closest to the most negative value to create all positive values
  left_join(meta, c("rarefyID" = "rarefyid"))

#find rarefyID's that have inf value for some metrics and exclude
cont_inf <- metrics %>% filter(is.infinite(value), !metric %in% c("qual.FRic",  "SES_qual.FRic")) %>% pull(rarefyID) 

#get rarefyID's that don't have enough null samples
missing_null <- bind_rows(metrics %>% 
  filter(n_missing_nulls == 1, commplete_null_samps == FALSE),
  metrics %>% filter(n_missing_nulls > 100)) %>%
  pull(rarefyID) %>%
  unique()

model_data <- metrics %>% 
  filter(!rarefyID %in% cont_inf, !rarefyID %in% missing_null) %>%
  group_by(metric) %>%
  mutate(study_id =  str_extract(rarefyID, "[^_]+")) %>%
  mutate(year_scaled = scale(year), 
         scale_center = attributes(year_scaled)$`scaled:center`, 
         scale = attributes(year_scaled)$`scaled:scale`) %>%
  ungroup()
```

####Data exploration

Visualize distributions of response
```{r}
model_data %>%
  filter(metric %in% c("FRic", "FEve", "FDiv", "FDis", "S", "Jaccard_base")) %>%
  ggplot() +
  geom_histogram(aes(x = logvalue),
                 bins = 60) +
  facet_wrap(~metric, scales = "free") +
  labs(title = "Distribution of Log values")

model_data %>%
  filter(metric %in% c("FRic", "FEve", "FDiv", "FDis", "S", "Jaccard_base")) %>%
  ggplot() +
  geom_histogram(aes(x = value),
                 bins = 60) +
  facet_wrap(~metric, scales = "free") +
  labs(title = "Distribution of raw values")
```

Fit a single model to play around with 
```{r}
test_data <- model_data %>% 
  filter(metric == "FRic") %>%
  mutate(study_id = as.factor(study_id))

#lognormal
ln_fit <- lmer(logvalue ~ year_scaled + (year_scaled|study_id/rarefyID), data = test_data,
               control = lmerControl(optCtrl = list(maxit = 1e9,
                                                    maxfun = 1e9,
                                                    xtol_abs = 1e-11,
                                                    ftol_abs = 1e-11,
                                                    maxeval = 1e9)))

gamma_fit <- glmer(value ~ year_center + (year_center|study_id/rarefyID), data = test_data, family = Gamma)

poiss_fit <- glmer(value ~ year_center + (year_center|study_id/rarefyID), data = test_data, family = poisson(link = "log"))

nb_fit <- glmer.nb(value ~ year_center + (year_center|study_id/rarefyID), data = test_data)
```


Get p-values for blups 
```{r}
cV <- ranef(ln_fit, effects = "ran_vals", drop = TRUE)
ranvar <- attr(cV[[1]], "postVar")

ng <- dim(ranvar)[3]
np <- dim(ranvar)[2]
mm <- matrix(ranvar[cbind(rep(seq(np),ng),
             rep(seq(np),ng),
             rep(ng,each=np))],
       byrow=TRUE,
       nrow=ng)

sumVar <- vcov(ln_fit)[1,1]+mm[,1]

year_scaled_var <- tidy(ln_fit) %>%
  filter(term == "year_scaled") %>% 
  mutate(var = std.error*std.error) %>%
  pull(var) 

study_ests <- broom.mixed::tidy(ln_fit, effects="ran_vals") %>%
  filter(group == "study_id", term == "year_scaled") %>% 
  rename(cond.std.error = std.error) %>%
  mutate(cond.var = cond.std.error*cond.std.error, 
         var = cond.var + year_scaled_var,
         std.error = sqrt(var),
         upr.ci = estimate + (2*std.error),
         lwr.ci = estimate - (2*std.error),
         sig = case_when(
           lwr.ci < 0 & upr.ci > 0 ~ FALSE,
           TRUE ~ TRUE
         ))
```

Look for best optimizer using `allFit()`, doesn't look like any of them work
```{r}
#find best optimizer
#lognormal fit
ln_optims <- allFit(ln_fit, maxfun = 1e5)

is.OK <- sapply(ln_optims, is, "merMod")
ln_optims.OK <- ln_optims[is.OK]
lapply(ln_optims.OK,function(x) x@optinfo$conv$lme4$messages)

```

Let's try all the options for both optimix and nloptwrap, first for the generalized option w/Gamma distribution
```{r}
optimx_options <- c("L-BFGS-B", "nlminb", "nlm", "bobyqa", "nmkb", "hjkb")

for(i in 1:length(optimx_options)){
  model_flex <- lmer(logvalue ~ year_center + (year_center|study_id/rarefyID), data = test_data,
                     control = lmerControl(optimizer = "optimx",
                                           optCtrl = list(method = optimx_options[i],
                                                                   maxit = 1e9)))
  if(is.null(model_flex@optinfo$conv$lme4$messages)){
    print(paste0("One of the optimx options, ", optimx_options[i],", worked!"))
    print(summary(model_flex))
    break
  }
}

algoptions <- c("NLOPT_LN_PRAXIS", "NLOPT_GN_CRS2_LM",
"NLOPT_LN_COBYLA", "NLOPT_LN_NEWUOA",
"NLOPT_LN_NEWUOA_BOUND", "NLOPT_LN_NELDERMEAD",
"NLOPT_LN_SBPLX", "NLOPT_LN_BOBYQA")

for(i in 1:length(algoptions)){
  model_flex <- lmer(logvalue ~ year_center + (year_center|study_id/rarefyID), data = test_data,
                     control = lmerControl(optimizer = "nloptwrap",
                                           optCtrl = list(algorithm = algoptions[i],
                                                          maxeval = 1e7,
                                                          xtol_abs = 1e-9,
                                                          ftol_abs = 1e-9)))
  if(is.null(model_flex@optinfo$conv$lme4$messages)){
    print(paste0("One of the nloptwrap options, ", algoptions[i],", worked!"))
    print(summary(model_flex))
    break
  }
}
```

```{r}

optimx_options <- c("L-BFGS-B", "nlminb", "nlm", "bobyqa", "nmkb", "hjkb")

for(i in 1:length(optimx_options)){
  model_flex <- glmer(value ~ (year|study_id/rarefyID), data = test_data, family = Gamma,
                     control = glmerControl(optimizer = "optimx",
                                           optCtrl = list(method = optimx_options[i],
                                                                   maxit = 1e9)))
    if(is.null(model_flex@optinfo$conv$lme4$messages)){
    print(paste0("One of the optimx options, ", optimx_options[i],", worked!"))
    print(summary(model_flex))
    break
  }
}

#nloptwrap
algoptions <- c("NLOPT_LN_PRAXIS", "NLOPT_GN_CRS2_LM",
"NLOPT_LN_COBYLA", "NLOPT_LN_NEWUOA",
"NLOPT_LN_NEWUOA_BOUND", "NLOPT_LN_NELDERMEAD",
"NLOPT_LN_SBPLX", "NLOPT_LN_BOBYQA")

for(i in 1:length(algoptions)){
  model_flex <- glmer(value ~ (year|study_id/rarefyID), data = test_data, family = Gamma,
                     control = glmerControl(optimizer = "nloptwrap",
                                           optCtrl = list(algorithm = algoptions[i],
                                                          maxeval = 1e7,
                                                          xtol_abs = 1e-9,
                                                          ftol_abs = 1e-9)))
  if(is.null(model_flex@optinfo$conv$lme4$messages)){
    print(paste0("One of the nloptwrap options, ", algoptions[i],", worked!"))
    print(summary(model_flex))
    break
  }
}

```

```{r}
test_data <- model_data %>% 
  filter(metric == "SES_FEve") %>%
  mutate(study_id = as.factor(study_id))

all_model <- lmer(value ~ year_scaled + taxa + realm + (year_scaled|study_id/rarefyID), 
                                 data = test_data)
```

