---
title: "BioTime"
author: "Kari Norman"
date: "4/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(lazyeval)
library(rdataretriever)

```

Import occurence data from Biotime
```{r}
#rdataretriever::install("biotime", connection = "csv", data_dir = here("data"))

data <- read_csv(here("data", "biotime_metadata.csv")) %>% filter(taxa %in% c("Birds", "Mammals")) %>%
  select(study_id, taxa) %>%
  left_join(read_csv(here("data", "biotime_query.csv")), by = "study_id")
  
```

Get mammal and trait data
```{r}
bird_trait <- read_csv(here("data/elton_traits/elton_traits_BirdFuncDat.csv"))
mamm_trait <- read.csv(here("data/elton_traits/elton_traits_MammFuncDat.csv"))
```

Check which authority would result in the most matches 
```{r}
library(taxadb)

get_match_counts <- function(data, species_col){
  species_col <- lazyeval::as_name(species_col)
  data %>% 
    select(!!species_col) %>% 
    drop_na() %>%
    distinct() %>%
    mutate(
      gbif = get_ids(!!species_col, "gbif"),
      col = get_ids(!!species_col, "col" ),
      itis = get_ids(!!species_col, "itis"),
      ncbi = get_ids(!!species_col, "ncbi"),
      wd = get_ids(!!species_col, "wd"  ),
      iucn = get_ids(!!species_col, "iucn"),
      ott = get_ids(!!species_col, "ott" ) 
    ) %>%
    #select(!!call("-", species_col)) %>%
    purrr::map_dbl(function(x) sum(!is.na(x)))
}

##Counts show that OTT is the best authority for both data sets
get_match_counts(data %>% filter(taxa == "Birds"), "genus_species")
get_match_counts(data, "genus_species")
get_match_counts(bird_trait, "scientific")
get_match_counts(mamm_trait, "scientific")
```

OTT is the best authority but doesn't have common names, so we use the next best ITIS
```{r}
#Getting matches by scientific name 
biotime <- data %>% 
  #filter(taxa == "Birds") %>%
  select(genus_species) %>%
  drop_na() %>%
  distinct() %>%
  mutate(id = get_ids(genus_species, "itis")) %>%
  left_join(data, by = "genus_species")

#Getting matches by sci name and common name 
biotime_ids <- by_name(unique(data$genus_species), "itis") %>%
  bind_rows(by_common(unique(data$genus_species), "itis")) %>%
  drop_na(acceptedNameUsageID)

#There is not a unique taxonID for each species, different pop's have different ID's for some marine mammals
#Names with more than one match that need to be resolved manually
#biotime_ids %>% group_by(sort) %>% filter(n()>1) %>% View()

biotime_data <- biotime_ids %>%
  group_by(sort) %>%
  filter(n() < 2) %>%
  ungroup(sort) %>%
  select(taxonID,input) %>%
  left_join(data, by = c("input" = "genus_species"))
```



