---
title: "Fishbase"
author: "Kari Norman"
date: "9/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rfishbase)

```

Potential tables of interest: diet, ecology, ecosystem, fecundity, fooditems, maturity, popchar, popgrowth, reproduc, spawning, speed

other: morphdat, oxygen

```{r}
tables <- c("diet", "ecology", "ecosystem", "fecundity", "fooditems", "maturity", "popchar", "popgrowth", "reproduc", "spawning", "speed", "morphdat", "oxygen")
columns <- purrr::map(tables, ~docs(table = .x)$column_name) %>% unlist()
```

download all the tables
```{r}
#diet <- diet()

eco <- ecology() %>% 
  select(-c(autoctr, StockCode, EcologyRefNo, DietRemark, FoodRemark, AddRems, OutsideHost, OHRemarks, InsideHost),
                            -ends_with("Ref"), -starts_with("Associations"))

ecosys <- ecosystem() %>%
  select(EcosystemType, Salinity, Climate, Polar, Boreal, Temperate)

fec <- fecundity()

food <- fooditems()

mat <- maturity()

```

