---
title: "BAT"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

Let's also do the functions from BAT package
```{r}
#function for getting PCA axes with at least 95% coverage
axes95 <- function(mat){
  axes <- pco(mat)
  eigen <- axes$eig
  
  threshold <- sum(eigen[eigen > 0]) * 0.95
  
  sums <- cumsum(eigen)
  num_axes <- Position(function(x) x > threshold, sums)
  
  return(num_axes)
}

get_BAT_fd <- function(data, filter_plot){
  require(BAT)
  require(StatMatch)
  require(labdsv)
  
  data <- data %>% filter(plot_id == filter_plot)
  
  print(max(data$record_id))
  
  species_mat <- data %>%
    select(year, id) %>% 
    distinct() %>%
    arrange(year, id) %>%
    mutate(present = 1) %>%
    spread(id, value = present, fill = 0) %>%
    column_to_rownames("year")
  
  trait_mat <- data %>%
    select(-c(taxa, record_id, day, month, year, sample_desc, id_species, 
              latitude, longitude, sum_abundance, sum_biomass, biotimeName, 
              traitName, scientificName)
    ) %>%
    distinct() %>%
    select_if(~ length(unique(.)) > 1) %>% #remove columns that have the same value for all columns
    mutate_at(vars(-id, -ends_with("5cat")), list(~scales::rescale(.,to=c(0, 1)))) %>% #rescale variables
    arrange(id) %>%
    column_to_rownames("id")
  
  #get PCA trait matrix
  trait_dist <- gower.dist(trait_mat)
  trait_pco <- pco(trait_dist, k = axes95(trait_dist))

  traits <- trait_pco$points
  rownames(traits) <- rownames(trait_mat)
  
  #getFD metrics
  kernelFD <- kernel.alpha(comm=as.matrix(species_mat),trait=traits,abund=FALSE,method="gaussian",return.hv=TRUE)
  hv <- kernelFD[[2]]
  
  disp <- kernel.dispersion(comm=hv,frac=0.1,func='dissimilarity') 
  div <- kernel.dispersion(comm=hv,frac=0.6, func='divergence')
  even <- kernel.evenness(comm=hv)
  
  results <- data.frame(richness = as.numeric(kernelFD[[1]]), disp, div, even) %>% 
    mutate(plot_id = filter_plot)
  
  return(results)
}

get_BAT_fd(biotime_traits, 376300153)
```


BAT
```{r}
library(BAT)

get_plot_BAT <- function(data, trait_range, occ_df, filter_plot) {
  sample_species_mat <- occ_df %>%
    filter(plot_id == filter_plot) %>%
    select(-c(richness, plot_id, n)) %>% #want only species x site info
    select_if(!colSums(.) %in% c(0, NA)) %>% #remove species that don't occur in the plot
    select(sort(tidyselect::peek_vars())) #sort columns to be in alphabetical order, required for dbFDI()
  
  traits <- colnames(data)[trait_range]
  sample_trait_mat <-
    clean_trait_matrix(get_trait_matrix(data = data, colnames(sample_species_mat), traits))
  
  #get distance matrix
  dist_traits <-  gowdis(sample_trait_mat)
  trait.pco <- dudi.pco(quasieuclid(dist_traits), scannf = FALSE, full = TRUE)
  
}

test <- get_plot_BAT(biotime_traits, 17:64, sample_occurrence, 5617)


ower.mat_spider <- gower.dist(traits)
euc.pco <- pco(gower.mat_spider,k=3)

barplot(euc.pco$eig)
(euc.pco$eig[1]+euc.pco$eig[2]+euc.pco$eig[3])/sum(euc.pco$eig[euc.pco$eig > 0]) #0.955 variance explained by first 3 axes

traits <- euc.pco$points
row.names(traits) <- row.names(traits2)
```

