---
title: "Check Coverage"
author: "Kari Norman"
date: "5/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
load(here::here("data", "biotime_data.rda"))
load(here::here("data", "elton_mamm.rda"))
load(here::here("data", "elton_bird.rda"))
load(here::here("data", "amphibio.rda"))
```

#Checking Coverage of ID's and trait data -> biotime

check if all bird & mammal biotime data w/id's has an elton match. There are 63 species without a match (54 are birds).
```{r}
no_trait <- biotime_data %>%
  filter(taxa %in% c("Birds", "Mammals")) %>%
  select(id, sourceName, taxa) %>%
  drop_na(id) %>%
  distinct() %>%
  filter(!id %in% elton_bird$id, !id %in% elton_mamm$id)

dim(no_trait)
```

and 19869 species without an ID, some of which are species codes
```{r}
biotime_data %>%
  #filter(taxa == "Birds") %>%
  select(id, sourceName, taxa) %>%
  filter(is.na(id)) %>%
  distinct() %>%
  dim()
```

Are there any studies for which we have trait data for all species?
```{r}
merge_data <- function(taxa, trait_data){
  biotime_data %>%
    select(-sourceName, -scientificName) %>%
  filter(taxa == taxa) %>%
  left_join(trait_data, by = "id",
            na_matches = "never")
}

get_coverage <- function(taxa_data){
  coverage <- taxa_data %>%
  group_by(study_id) %>%
  summarise(perc = sum(!is.na(sourceName))/n()) %>%
  arrange(desc(perc))
}

get_coverage(merge_data("Birds", elton_bird)) %>% View
get_coverage(merge_data("Mammals", elton_mamm)) %>% View()
get_coverage(merge_data("Amphibians", amphibio)) %>% View()
```

Get data w/traits for all studies that have >85% trait coverage
```{r}
#set coverage threshold for analysis dataset
percent <- 0.85

traits <- list(elton_bird, elton_mamm, amphibio)
taxa <- list("Birds", "Mammals", "Amphibians")

biotime_traits_list <- map2(taxa, traits, ~merge_data(taxa = .x, trait_data = .y))
coverage <- map_dfr(biotime_traits_list, get_coverage) %>%
  filter(perc > percent)

biotime_traits <- map_dfr(biotime_traits_list, ~drop_na(., scientificName)) %>%
  #bind_rows() %>%
  filter(study_id %in% coverage$study_id)
```

