---
title: "Biotime Database Access"
author: "Kari Norman"
date: "8/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DBI)
library(dbplyr)
library(tidyverse)

con <- dbConnect(
  drv = RMariaDB::MariaDB(), 
  dbname = "biotime",
  username = "root",
  password = "Ka1172353!", 
  host = "localhost"
)

biotime_sql <- tbl(con, "allrawdata") %>% 
  collect() %>% 
  rename_all(.funs = tolower) %>%
  select(-id_all_raw_data)
```

```{r}
dupes <- biotime_sql %>% group_by(study_id, plot, id_species, year, month, day) %>% filter(n() >1)

year_biotime <- biotime_sql %>% 
  group_by(id_species, plot, year, study_id) %>% 
  summarise(year_abun = sum(na.omit(abundance)), 
            year_biomass = sum(na.omit(biomass))) %>%
  left_join(tbl(con, "datasets") %>% select(taxa = TAXA, study_id = STUDY_ID) %>% collect()) %>%
  left_join(tbl(con, "species") %>% select(id_species = ID_SPECIES, genus_species = GENUS_SPECIES) %>% collect())

#should be zero to be appropriately aggregated
#year_biotime %>% group_by(study_id, plot, year, id_species) %>% filter(n()>1) %>% View()

usethis::use_data(year_biotime)
pins::pin(year_biotime, board = "github")
```

