---
title: "Check Coverage"
author: "Kari Norman"
date: "5/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(FD)
```

```{r}
load(here::here("data", "biotime_data.rda"))
load(here::here("data", "elton_mamm.rda"))
load(here::here("data", "elton_bird.rda"))
load(here::here("data", "amphibio.rda"))
```

#Checking Coverage of ID's and trait data -> biotime

check if all bird & mammal biotime data w/id's has an elton match. There are 63 species without a match (54 are birds).
```{r}
no_trait <- biotime_data %>%
  filter(taxa %in% c("Birds", "Mammals")) %>%
  select(id, sourceName, taxa) %>%
  drop_na(id) %>%
  distinct() %>%
  filter(!id %in% elton_bird$id, !id %in% elton_mamm$id)

dim(no_trait)
```

and 19869 species without an ID, some of which are species codes
```{r}
biotime_data %>%
  #filter(taxa == "Birds") %>%
  select(id, sourceName, taxa) %>%
  filter(is.na(id)) %>%
  distinct() %>%
  dim()
```

Are there any studies for which we have trait data for all species?
```{r}
merge_data <- function(taxa, trait_data){
  biotime_data %>%
    select(-sourceName, -scientificName) %>%
  filter(taxa == taxa) %>%
  left_join(trait_data, by = "id",
            na_matches = "never")
}

get_coverage <- function(taxa_data){
  coverage <- taxa_data %>%
  group_by(study_id) %>%
  summarise(perc = sum(!is.na(sourceName))/n()) %>%
  arrange(desc(perc))
}

get_coverage(merge_data("Birds", elton_bird)) %>% View
get_coverage(merge_data("Mammals", elton_mamm)) %>% View()
get_coverage(merge_data("Amphibians", amphibio)) %>% View()
```

Get data w/traits for all studies that have >85% trait coverage
```{r}
#set coverage threshold for analysis dataset
percent <- 0.85

traits <- list(elton_bird, elton_mamm, amphibio)
taxa <- list("Birds", "Mammals", "Amphibians")

biotime_traits_list <- map2(taxa, traits, ~merge_data(taxa = .x, trait_data = .y))
coverage <- map_dfr(biotime_traits_list, get_coverage) %>%
  filter(perc > percent)

biotime_traits <- map_dfr(biotime_traits_list, ~drop_na(., scientificName)) %>%
  filter(study_id %in% coverage$study_id)
```

```{r}
usethis::use_data(biotime_traits)
```

Get FD metrics for each study 
```{r}
load(here::here("data", "biotime_traits.rda"))

get_fd <- function(data){
  #print(max(data$record_id))
  species_mat <- data %>%
    select(year, id) %>% 
    arrange(year, id) %>%
    mutate(present = 1) %>%
    spread(id, value = present, fill = 0) %>%
    select(-year)
  
  years <- data %>% 
    select(year) %>%
    distinct() %>%
    arrange(year)
  
  trait_mat <- data %>%
    select(id, diet_inv, diet_vend, diet_vect, diet_vfish, diet_vunk, diet_scav, diet_fruit, 
           diet_nect, diet_seed, diet_planto, diet_certainty, forstrat_watbelowsurf,
           forstrat_wataroundsurf, forstrat_ground, forstrat_understory, forstrat_midhigh,
           forstrat_canopy, forstrat_aerial, pelagicspecialist, forstrat_speclevel, nocturnal, 
           bodymass_value, bodymass_speclevel, forstrat_value, activity_nocturnal, activity_crepuscular, 
           activity_diurnal, Fos, Ter, Aqu, Arb, Leaves, Flowers, Seeds, Fruits, Arthro, Vert, 
           Diu, Noc, Crepu, Wet_warm, Wet_cold, Dry_warm, Dry_cold, Body_mass_g, Age_at_maturity_min_y, 
           Age_at_maturity_max_y, Body_size_mm, Size_at_maturity_min_mm, Size_at_maturity_max_mm, 
           Longevity_max_y , Litter_size_min_n, Litter_size_max_n, Reproductive_output_y, 
           Offspring_size_min_mm, Offspring_size_max_mm, Dir, Lar, Viv, OBS 
    ) %>%
    distinct() %>%
    select_if(~ length(unique(.)) > 1) %>% #remove columns that have the same value for all columns
    mutate_at(vars(-id), list(~scales::rescale(.,to=c(0, 1)))) %>% #rescale variables
    arrange(id) %>%
    column_to_rownames("id")
  
  as.tibble(dbFD_joggle(trait_mat, species_mat, w.abun = FALSE))[,1:8] %>%
    cbind(years, .)
}

get_fd_safe <- possibly(get_fd, NA)

test_data <- biotime_traits %>% 
  group_by(study_id, plot) %>%
  nest() %>%
  mutate(metrics = map(data, ~get_fd_safe(.x))) %>%
  filter(!is.na(metrics)) %>%
  select(-data) %>%
  unnest()
```

