---
title: "Models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#library(moderndive)
library(lme4)
library(broom.mixed)
```

Get data and put it in long form 
```{r}
pins::board_register_github(repo = "karinorman/biodivTS_data", branch = "master")

metrics <- pins::pin_get("rarefied-medians", board = "github") %>%
  select(-cYEAR) %>%
  pivot_longer(., cols = setdiff(everything(), one_of("rarefyID", "STUDY_ID", "SamplePool", "SampleN", "num_years", "duration", "startYear", "endYear", "YEAR", "cell", "rarefied", "type", "realm", "climate", "habitat", "biome_map", "taxa", "organisms", "cent_lat", "cent_long", "abundance_type", "BROAD_TYPE", "taxa_mod", "climate_mod")), names_to = "metric", values_to = "value") %>%
  rename_with(tolower, .cols = setdiff(everything(), one_of("rarefyID")))  %>%
  mutate(logvalue = log(value + abs(floor(min(na.omit(value)))))) # create a column for log transformation that adds the absolute value integer closest to the most negative value to create all positive values
```
####Data exploration

How many years are missing FD metrics? Only a handful! Let's exclude them so we can get an accurate view of the number of years for which we have data for each timeseries                                                                                                     
```{r}
no_fd_years <- metrics %>%
  filter(metric %in% c("FRic", "FEve", "FDiv", "FDis"), is.na(value))

dim(no_fd_years)

metrics <- setdiff(metrics, no_fd_years)
```

Visualize number of years for each timeseries
```{r}
hist_numYears <- metrics %>%
  select(year, rarefyID) %>% 
  distinct() %>% 
  count(rarefyID, name = "num_years") %>% 
  ggplot() +
  geom_histogram(aes(x = num_years),
                 binwidth = 2) +
  scale_x_continuous(name = 'Number of years sampled',
                     breaks = c(2,4,8,16,32,48,64,96)) +
  #scale_y_continuous(breaks = c(0,2500,5000,7500,10000,12500, 15000, 17500, 20000,22500)) +
  labs(tag = 'B',
       y = 'Number of cells') +
  theme_bw() +
  theme(panel.grid.minor.x = element_blank())
```

Fit GLM to overall metric trend
```{r}
# model for overall trend (random effect w/varying intercept)
## should be GLS according to Dornelas supplement, but glmer isn't happy
metric_mean_fit <- metrics %>%
  filter(!is.na(value)) %>%
  group_nest(metric) %>%
  mutate(model = map(data, ~lmer(logvalue ~ year + (1|study_id) + (1|rarefyID), data = .x)))

metric_mean_coef <- metric_mean_fit %>%
  mutate(coef = map(model, tidy)) %>% 
  #mutate(confint = map(model, confint)) %>%
  select(-data, -model) %>% 
  unnest(cols = c(coef))

# model for overall trend (random effect w/varying intercept and slope)
# metric_slope_fit <- metrics %>%
#   filter(!is.na(value)) %>%
#   group_nest(metric) %>%
#   mutate(model = map(data, ~lmer(logvalue ~ year + (1 + year | rarefyID), data = .x)))
# 
# metric_slope_coef <- metric_slope_fit %>%
#   mutate(coef = map(model, tidy)) %>% 
#   #mutate(confint = map(model, confint)) %>%
#   select(-data, -model) %>% 
#   unnest(cols = c(coef))
```


```{r}
indiv_ts_fit <- metrics %>% 
  filter(!is.na(value)) %>%
  group_by_at(setdiff(names(metrics), c("year", "value"))) %>%
  filter(n_distinct(year) > 1) %>% #filter out rarefyID's that don't have multiple years after dropping Na's
  group_nest() %>%
  mutate(model = map(data, ~ lm(value ~ year, data = .x)))

indiv_ts_coef <- indiv_ts_fit %>%
  mutate(coef = map(model, tidy)) %>% 
  select(-data, -model) %>% 
  unnest(cols = c(coef))
```

Plot of S and diversity metrics
```{r}
indiv_ts_coef %>%
  filter(term == "year", metric %in% c("FRic", "FEve", "FDiv", "FDis", "S")) %>%
  select(metric, estimate) %>% 
  ggplot() +
  geom_histogram(aes(x = estimate)) + #,
                 #binwidth = 2) +
  scale_x_continuous(name = 'slope') +
  #scale_y_continuous(breaks = c(0,2500,5000,7500,10000,12500, 15000, 17500, 20000,22500)) +
  labs(tag = 'B',
       y = 'Number of cells') +
  theme_bw() +
  theme(panel.grid.minor.x = element_blank()) +
  facet_wrap(vars(metric), scales = "free")
```

