---
title: "Rarefied Null Models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(FD)
library(furrr)

pins::board_register_github(repo = "karinorman/biodivTS_data", branch = "master")
```

Get dataframe of filenames and corresponding rarefyID's
```{r}
path <- here::here("data", "rarefied_samples")
files <- list.files(path) %>%
  paste0(path, "/", .)

# samples <- purrr::map_dfr(files, function(x) {load(x)
#   return(rare_comm_save)
# 	}) %>% distinct()
```

Function to get all rarefied samples for an ID
```{r}
# get_rarefy_samps <- function(id, path = here::here("data", "rarefied_samples")){
#   print(id)
#   samp_data <- list.files(path = path, pattern = paste0( "*.", id, ".*")) %>% 
#     paste0(path, "/", .) %>%
#      purrr::map_dfr(., function(x) {load(x)
#        return(rare_comm_save)
#        }) 
#   return(samp_data)
# }
```
Get species pools for each timeseries
```{r}
bt_grid_filtered <- pins::pin_get("bt-traitfiltered", board = "github")
trait_ref <- pins::pin_get("trait-ref", board = "github")

species_pools <- bt_grid_filtered %>%
  select(rarefyid, species) %>% 
  distinct()

rm(bt_grid_filtered)
```

Simulation functions
```{r}
get_plot_sample <- function(file, n){
  #print(filter_id)
  load(file)
  comm <- rare_comm_save %>%
    pivot_longer(cols = starts_with("ITIS"), names_to = "species", values_to = "weight") %>%
    filter(weight != 0) %>%
    rename_with(tolower)
  
  filter_rarefyid <- unique(comm$rarefyid) %>% unlist()
  samp_rarefy_resamp <- unique(comm$rarefy_resamp) %>% unlist()
  print(filter_rarefyid)
  
  #check that there are at least two species for all years, otherwise stop sampling
  species_count <- comm %>% select(year, species) %>% count(year)
  if (min(species_count$n) < 2){
    save_dir <- here::here("data", "no_null_sample")
    fs::dir_create(save_dir)
    write.csv(rare_comm_save, paste0(save_dir, "/", filter_rarefyid, "_samp", samp_rarefy_resamp, ".csv"))
    return()
  }
  
  # plot_data <- data %>% filter(rarefyID == filter_id) %>%
  #   select(year, id, weight)
  
  species_pool <- species_pools %>%
    filter(rarefyid == filter_rarefyid) %>%
    pull(species) %>%
    na.omit() %>%
    unique() #get column of unique scientific names
  
  get_samp_species <- function(data){
    samp_species <- sample(species_pool, n_distinct(data$species))
    samp_abun <- sample(data$weight)
      
    df <- as_tibble(cbind(samp_species, samp_abun)) %>% mutate(year = unique(data$year))
    return(df)
  }
  
  site_samples <- data.frame()
  for (j in 1:n){
    iter_samples <- data.frame()
    for(i in unique(comm$year)){
      year_data <- comm %>% filter(year == i)
      iter_samples <- rbind(iter_samples, get_samp_species(year_data))
    }
    site_samples <- rbind(site_samples, iter_samples %>% mutate(n = j))
  }
  plot_samples <- site_samples %>%
    mutate(rarefyid = filter_rarefyid, rarefy_resamp = samp_rarefy_resamp) %>%
    pivot_wider(names_from = samp_species, values_from = samp_abun)
  
  save_dir <- here::here("data", "null_samples")
  fs::dir_create(save_dir)
  write.csv(plot_samples, paste0(save_dir, "/", filter_rarefyid, "_samp", samp_rarefy_resamp, ".csv"))
  
  return(plot_samples)
}
```

Get sample dataframe
```{r}
future::plan(multiprocess, workers = 30)
sample_occurrence <- future_map(files, get_plot_sample, n = 500, 
                                .options = furrr_options(seed = TRUE)) #%>%
  # bind_rows() %>%
  # replace(is.na(.), 0)
```
Figure out which samples didn't get null samples
```{r}
null_files <- list.files(here::here("data", "null_samples")) %>%
  paste0(here::here("data", "null_samples"), "/", .)

nulls <- as.data.frame(null_files) %>% 
  mutate(store_nums = str_extract_all(null_files, "[0-9]+")) %>%
  unnest_wider(store_nums) %>%
  unite(rarefyid, `...1`, `...2`, sep = "_") %>% 
  rename(rarefy_resamp = `...3`) %>%
  mutate(rarefy_files = paste0(path, "/count_cell", rarefyid, "_sample", rarefy_resamp, ".rda"))

# null_samples <- map_dfr(null_files, ~read_csv(.x) %>% select(rarefyid, rarefy_resamp) %>% distinct()) %>%
#   mutate(rarefy_samp_file = paste0(path, "/count_cell", rarefyid, "_sample", rarefy_resamp, ".rda")) 

missing_files <- setdiff(files, nulls$rarefy_files)

future::plan(multiprocess)
sample_occurrence <- future_map(missing_files, get_plot_sample, n = 500,
                                .options = furrr_options(seed = TRUE)) %>%
  bind_rows() %>%
  replace(is.na(.), 0)
```

```{r}
get_nullplot_FD <- function(file_path, traits, ...) {
  library(FD)
  
  plot_samples <- read_csv(file_path) %>% 
    replace(is.na(.), 0)

  sample_species_mat <- plot_samples %>%
    select(starts_with("ITIS")) %>% #want only species x site info
    select(sort(tidyselect::peek_vars())) #sort columns to be in alphabetical order, required for dbFDI()
  
  print(head(sample_species_mat))
  trait_mat <- get_traitMat(colnames(sample_species_mat), trait_data = traits) 
  
  save_dir <- here::here("data", "fd_null_output")
  fs::dir_create(save_dir)
  
  get_FD_safe <- possibly(get_FD, otherwise = data_frame())
  
  max_val <- max(unlist(map(sample_species_mat, max)))
  if(max_val > 1){
    FD_mets <- get_FD_safe(species_mat = sample_species_mat, trait_mat = trait_mat, year_list = plot_samples$year,
                           data_id = unique(plot_samples$rarefyid), samp_id = unique(plot_samples$rarefy_resamp),
                           w.abun = TRUE, m = "min", corr = "cailliez")
  }else{
    FD_mets <- get_FD_safe(species_mat = sample_species_mat, trait_mat = traits, year_list = plot_samples$year,
                           data_id = unique(plot_samples$rarefyid), samp_id = unique(plot_samples$rarefy_resamp),
                           w.abun = FALSE, m = "min", corr = "cailliez")
  }
  
  sample_fd <- FD_mets$fd_met %>% cbind(plot_samples %>% select(rarefyid, rarefy_resamp, n))

  setwd(here::here())
  write_tsv(sample_fd, paste0(save_dir, "/null_rarefy", unique(plot_samples$rarefyid), "samp",  unique(plot_samples$rarefy_resamp), ".tsv"))
  
  return(sample_fd)
}

null_files <-  dir(here::here("data", "null_samples"), "*.csv") %>%
  paste0(here::here("data", "null_samples"), "/", .)

#in order to get this to run in parallel, must devtools::install() for the biodivTS package
plan(multiprocess, workers = 30)
null_FD <- future_map_dfr(null_files, ~get_nullplot_FD(.x, traits = trait_ref),
                           .options = furrr_options(seed = TRUE))
```

Create Null table
```{r}
path <- here::here("data", "fd_null_output")
null_files <-  dir(path, "*.tsv") %>%
  paste0(path, "/", .)

process_nulls <- function(file_path, n){
  data <- read_tsv(file_path) %>%
    rename(richness = nbsp) %>%
    select(-sing.sp) %>%
    group_by(year)
  
  means <- data %>%
    select(-rarefyid, -richness) %>%
    summarise(across(everything(), mean)) %>%
    pivot_longer(cols = -year, names_to = "metric", values_to = "mean")
  
  sds <- data %>%
    select(-rarefyid, -richness) %>%
    summarise(across(everything(), sd)) %>%
    pivot_longer(cols = -year, names_to = "metric", values_to = "sd")
  
  stats <- left_join(means, sds, by = c("year", "metric")) %>%
    left_join(data %>% select(year, rarefyid, rarefy_resamp, richness) %>% distinct(), by = "year") %>%
    mutate(se = sd/sqrt(n),
           lowerCI = mean - qt(0.975, n - 1) * se, 
           upperCI = mean + qt(0.975, n - 1) * se)  %>%
    select(year, rarefyid, everything())
  
  return(stats)
}

plan(multiprocess)
null_table <- future_map_dfr(null_files, process_nulls, n = 500)

usethis::use_data(null_table)
pins::pin(null_table, board = "github")
```


