---
title: "null_model"
author: "Kari Norman"
date: "6/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(biodivTS)
library(FD)
library(furrr)

pins::board_register_github(repo = "karinorman/biodivTS", branch = "master")
```

Create null models that would be transferable to any timeseries by treating the species pool as all species observed across the timeseries.

Simulation functions
```{r}
get_plot_sample <- function(data, filter_plot, n){
  print(filter_plot)
  plot_data <- data %>% filter(plot_id == filter_plot) %>%
    select(year, id, weight)
  
  species_pool <- plot_data %>%
    pull(id) %>%
    na.omit() %>%
    unique() #get column of unique scientific names
  
  get_samp_species <- function(data){
    samp_species <- sample(species_pool, n_distinct(data$id))
    samp_abun <- sample(data$weight)
      
    df <- as_tibble(cbind(samp_species, samp_abun)) %>% mutate(year = unique(data$year))
    return(df)
  }
  
  site_samples <- data.frame()
  for (j in 1:n){
    iter_samples <- data.frame()
    for(i in unique(plot_data$year)){
      year_data <- plot_data %>% filter(year == i)
      iter_samples <- rbind(iter_samples, get_samp_species(year_data))
    }
    site_samples <- rbind(site_samples, iter_samples %>% mutate(n = j))
  }
  plot_samples <- site_samples %>%
    mutate(plot_id = filter_plot) %>%
    pivot_wider(names_from = samp_species, values_from = samp_abun)
  
  save_dir <- here::here("data", "null_samples")
  fs::dir_create(save_dir)
  write.csv(plot_samples, paste0(save_dir, "/", filter_plot, "_samps.csv"))
  
  return(plot_samples)
}
```

Get dataframe of samples for each plot and corresponding species and trait matrices
```{r}
biotime_traits <- pins::pin_get("biotime-traits", board = "github")

n = 100

#get the plots that meet our criteria for calculating FD
sample_plots <- biotime_traits %>%
  filter(!is.na(plot)) %>% #remove unlabeled plots 
  group_by(plot_id, year) %>%
  filter(n_distinct(id) > 4) %>%
  group_by(plot_id) %>%
  filter(n_distinct(year) > 4) %>%
  ungroup()

trait_data <- sample_plots %>% 
  select(-c(biotimeName, taxa, id_species, plot, year, weight, 
            traitName, scientificName, plot_id, study_id)) %>%
  distinct()
```

Get sample dataframe
```{r}
future::plan(multiprocess)
sample_occurrence <- future_map(unique(sample_plots$plot_id), get_plot_sample, data = sample_plots, n = n) %>%
  bind_rows() %>%
  replace(is.na(.), 0)

files <-  dir(here::here("data", "null_samples"), "*.csv")
sample_occurrence <- files %>%
  paste0(here::here("data", "null_samples"), "/", .) %>%
  map_dfr(~read_csv(.x) %>% mutate(plot_id = as.character(plot_id)) %>% replace(is.na(.), 0))

pins::pin(sample_occurrence, board = "github")
sample_occurrence <- pins::pin_get("sample_occurrence", board = "github")
```

```{r}
get_plot_FD <- function(traits, occ_df, filter_plot, ...) {
  plot_samples <- occ_df %>%
    filter(plot_id == filter_plot)
    
  sample_species_mat <- plot_samples %>%
    select(-c(year, plot_id, n)) %>% #want only species x site info
    select_if(!colSums(na.omit(.)) %in% c(0, NA)) %>% #remove species that don't occur in the plot
    select(sort(tidyselect::peek_vars())) #sort columns to be in alphabetical order, required for dbFDI()
  
  trait_mat <- traits %>%
    filter(id %in% colnames(sample_species_mat)) %>%
    select_if(~ length(unique(na.omit(.))) > 1)  #remove columns that have the same value for all columns
  
  #get binary variables so they can be excluded from rescaling 
  bin_vars <- map(trait_mat, ~ all(na.omit(.) %in% 0:1))
    
  trait_mat <- trait_mat %>%
    mutate_at(vars(-c(id, names(bin_vars[bin_vars == TRUE])), -ends_with("5cat")), 
              list(~as.numeric(scale(.)))) %>% #rescale variables, not binary or categorical
    arrange(id) %>%
    column_to_rownames("id")
  
  save_dir <- here::here("data", "fd_null_output")
  fs::dir_create(save_dir)
  
  #the convexhull c code creates an output file of vertices, in order to not have multiple threads writing
  #to the same file we have to create individual working directories
  tmp_dir <- paste0(save_dir, "/tmp", "/tmp_", filter_plot)
  fs::dir_create(tmp_dir)
  setwd(tmp_dir)
  
  print(filter_plot)
  sample_fd <- as.data.frame(dbFD_joggle(x = trait_mat, a = sample_species_mat, w.abun = TRUE, ...)) %>%
    cbind(plot_samples %>% select(year, plot_id, n))
  
  setwd(here::here())
  write_tsv(sample_fd, paste0(save_dir, "/null", filter_plot, ".csv"))
  
  # df <- occ_df %>%
  #   filter(plot_id == filter_plot) %>%
  #   select(richness, plot_id, n) %>%
  #   bind_cols(sample_fd) %>%
  #   mutate(merge_test = case_when(richness == nbsp ~ TRUE,
  #                                 TRUE ~ FALSE))
  # 
  # if (sum(df$merge_test) != dim(df)[1])
  #   warning("richness and region columns may not have been appropriately joined with FD data")
  
  return(sample_fd)
}

null_FD <- map_dfr(unique(sample_plots$plot_id)[1:3], get_plot_FD, 
                   traits = trait_data, occ_df = sample_occurrence,
                   m = "min", corr = "cailliez")
```

Calculate null models in parallel
```{r}
#number of chunks to split original dataset into 
num_groups = 4

plot_sizes <- sample_plots %>%
  count(plot_id) %>%
  arrange(desc(n)) %>%
  mutate(group = rep_len(1:num_groups, dim(.)[1]))

get_parallel_FD <- function(group_num){
  group_plots <- plot_sizes %>% filter(group == group_num)
  group_data <- sample_occurrence %>% filter(plot_id %in% group_plots$plot_id)
  group_trait_data <- trait_data %>% filter(id %in% colnames(group_data)[-(1:3)])
  
  future::plan(multiprocess)
  fd <- map_dfr(group_plots$plot_id[1:3], get_plot_FD,
                traits = group_trait_data, occ_df = group_data,
                m = "min", corr = "cailliez")
    #future_map(group_plots$plot_id, get_fd_safe, data = group_data)
  
  print(group_num)
  return(fd)
}

fd <- map_dfr(1:num_groups, get_parallel_FD)
```

BAT
```{r}
library(BAT)

get_plot_BAT <- function(data, trait_range, occ_df, filter_plot) {
  sample_species_mat <- occ_df %>%
    filter(plot_id == filter_plot) %>%
    select(-c(richness, plot_id, n)) %>% #want only species x site info
    select_if(!colSums(.) %in% c(0, NA)) %>% #remove species that don't occur in the plot
    select(sort(tidyselect::peek_vars())) #sort columns to be in alphabetical order, required for dbFDI()
  
  traits <- colnames(data)[trait_range]
  sample_trait_mat <-
    clean_trait_matrix(get_trait_matrix(data = data, colnames(sample_species_mat), traits))
  
  #get distance matrix
  dist_traits <-  gowdis(sample_trait_mat)
  trait.pco <- dudi.pco(quasieuclid(dist_traits), scannf = FALSE, full = TRUE)
  
}

test <- get_plot_BAT(biotime_traits, 17:64, sample_occurrence, 5617)


ower.mat_spider <- gower.dist(traits)
euc.pco <- pco(gower.mat_spider,k=3)

barplot(euc.pco$eig)
(euc.pco$eig[1]+euc.pco$eig[2]+euc.pco$eig[3])/sum(euc.pco$eig[euc.pco$eig > 0]) #0.955 variance explained by first 3 axes

traits <- euc.pco$points
row.names(traits) <- row.names(traits2)
```

