---
title: "Functional trait data tell new story about biodiversity change"
author: 
  - name: "Kari E A Norman"
    affiliation: ucb
  - name: "Carl Boettiger"
    affiliation: ucb, ropensci
address:
  - code: ucb
    address: "Dept of Environmental Science, Policy, and Management, University of California Berkeley, Berkeley CA 94720-3114, USA"
  - code: ropensci
    address: "The rOpenSci Project, University of California Berkeley, Berkeley CA 94720-3114, USA" 
abstract: |

journal: "Ecography"
date: "`r Sys.Date()`"
bibliography: refs.bib
layout: 3p
header-includes:
   - \usepackage{lineno}
   - \linenumbers
output: word_document
  #rticles::elsevier_article:
   # includes:
    #  in_header: preamble.tex
editor_options: 
  markdown: 
    wrap: 72
---

### Introduction

Ecological communities are experiencing unprecedented change as a result
of anthropogenic pressures such as climate change, land use change, and
invasive species. Impacts of these pressures are well documented at a
global scale by an accelerating global extinction rate [@barnosky2011],
and fundamental changes in some of the most well-studied systems (e.g.
coral bleaching). At the local scale however, species diversity tells a
different story. Recent synthesis of local trends in biodiversity over
time have found no net change in local biodiversity despite ongoing
species turnover [@brown2001; @dornelas2014; @vellend2013; @vellend2017]
and evidence of a decoupling of community composition from richness
[[@brose2016]; [@gotelli2017]. Potential hypothesis for the balance of
etc..<!-- potential indication of biological homogenization due to shifting ranges and/or invasive species-->
While communities are clearly changing, our most common species-based
approaches do not fully capture the nature of that change.

Functional diversity offers a potentially powerful alternative for
detecting and describing community change by providing a mechanistic
link between the organisms in a system and the processes they perform
[@mcgill2006]. By summarizing functional traits rather than species,
functional diversity metrics capture the disproportionate impact of
losses or gains of functionally unique species. Functional diversity
metrics are therefore particularly well suited for addressing change in
communities with constant species richness.

Functional diversity also has the potential to shed light on critical
ecosystem and community processes potentially impacted by anthropogenic
change. For example, there is increasing evidence that functional
diversity is a better predictor of ecosystem function than species-based
metrics [@cadotte2011; @gagic2015], and that different facets of
functional diversity also play a role in maintaining ecosystem stability
[@craven2018; @morin2014]. Further, biogeographic assessments of
functional diversity may give foundational insight into how community
assembly plays out across systems [@violle2014; @weiher2011].

<!-- What can we say about how global change is impacting:stability, resilience, function, assembly, ecosystem processes (and ecosystem services) - need a functional grounding for all those concepts. Link specific patterns in FD metrics to impacts on those concepts. -->

<!-- paragraph about what we already know about global functional changes -->

Assessments of broad-scale temporal change in functional diversity have
previously been limited by a lack of functional trait data. The majority
of work has therefore focused largely on system-specific studies with
traits collected *in situ*. Ongoing efforts to assemble functional
traits for a variety of taxa have made synthesis of existing community
assemblage data and functional traits possible for the first time,
providing initial looks at how functional diversity changes on a
broad-scale for specific taxa (e.g. fish[@trindade-santos2020], birds
[@jarzyna2016; @barnagaud2017]).
<!-- so what do these studies say? does that go here? --> However, to
date there has been no cross-taxa assessment of functional change
through time across a broad geographic and taxonomic extent.

Here we perform the first multitaxa, multisystem assessment of
functional diversity change through time. We assess thousands of mammal,
bird, and amphibian functional diversity timeseries to 1) determine how
functional diversity change compares to species change and 2) identify
three distinct types of functional change common across communities.
While our data represent the largest collection of functional diversity
timeseries to date, they are not a representative sample of systems
experiencing biodiversity change. We do not therefore seek to classify
the global trend in functional diversity change, but rather assess the
utility of a functional lens in understanding biodiversity change.

### Material and Methods

#### *Data*

We obtained mammal, bird, and amphibian timeseries from the Biotime
database, a global repository of high quality community assemblage
timeseries. All studies included in the database follow consistent
sampling protocols and represent full assemblages rather than population
of single species. [@dornelas2018]. Following best practices for the
database [@blowes2019] studies with multiple sample locations were split
into individual timeseries following a standardized scale. Scale was set
by a global grid with cell size determined based on the sample extent of
studies with only a single location (see [@dornelas2018] for details on
how sample extents were defined), with the area of each cell set to one
standard deviation away from the mean of the single extent locations.
All samples from a study within a single cell were considered to be a
single timeseries, and species abundances were combined for all samples.

We gathered trait data from the Elton Trait Database (mammals and birds;
[@wilman2014]) and Amphibio (amphibians, [@oliveira2017]). These
databases include species-level means for traits that best define
species' function in the community including body size, diet, and
behavioral characteristics <!-- what's in the amphibian database? -->.
For the full list of traits included in the analysis see the
supplemental materials.
<!-- limitations of species level trait data? -->

In order to ensure taxonomic consistency across datasets, Biotime
species were paired with trait data based on their species identifier
from the Integrated Taxonomic Information System database (citation),
obtained through the taxadb R package [@norman2020]. If more than one
species in the assemblage data resolved to the same identifier,
observations were considered the same species. For trait data, traits
for all species of the same identifier were averaged. Only studies with
at least 75% trait coverage were included. In order to have a sufficient
number of species to calculate functional diversity metrics years with
fewer than 4 species observed were excluded.

Many studies had a variable number of samples within years. To account
for this inconsistency in sampling effort we used sample-based
rarefaction by bootstrap resampling within years for each timeseries
based on the smallest number of samples in a year for that timeseries.

Our final dataset included 2439 timeseries from 54 studies in 21
countries and 15 biomes. Only four studies (consisting of 11 timeseries)
come from Amphibian studies due to the limited availability of amphibian
timeseries and low species richness values for assemblages. For a full
breakdown of studies and their characteristics see the supplement.

#### *Diversity Metrics*

We calculated yearly metrics of functional and species diversity for
each timeseries. Species-based metrics include species richness (*S*)
and Jaccard similarity (*J*) as a measure of turnover. Jaccard
similarity was calculated relative to the first observed year for a
timeseries. A negative trend would therefore indicate increasing
turnover.

Functional diversity metrics were calculated using the dbFD function
from the FD R package. Here we report functional richness (*FRic*),
functional evenness (FEve), and functional diveregence (FDiv) which
together describe three complementary characteristics of the functional
space [@mason2005]. FRic assesses the volume of the trait space occupied
by species in the community. FEve describes how species are distributed
across the trait space and how abundance is distributed across species.
FDiv measures the degree to which species and their abundances maximize
differences in the functional space. Higher values of FDiv therefore
correspond to communities where many highly abundant species are on the
edges of the trait space.

All available trait data for each study were included in functional
diversity calculations with the exception of traits that were the same
value for all observed species in the study. All continuous traits were
z-score scaled to give each trait equal weight in the trait space
[@leps2006; @schleuter2010]. The number of trait axes was limited to the
maximum number of traits that fulfills the criteria $s >= s^t$, where
$s$ is the number of species and \$t\$ is the number of traits. This
restriction allows for a sufficient number of axes to capture the trait
space while maintaining computational feasibility. Metrics incorporated
weighting based on species abundance where available.

#### *Null Models*

We corrected for bias in functional diversity metrics due to changes in
species richness by calculating the standardized effect size (SES) for
each metric from null estimates [@swenson2012]. Null model corrections
allow us to assess the degree to which the observed functional diversity
metric deviates from the value expected by chance in a randomly
assembled community. Null estimates were calculated for each rarefied
sample by randomly sampling species from the species pool for each year
and randomly assigning observed abundances to species. Species pools
included all species observed for a timeseries. This process was
repeated 500 times to get an estimate and standard deviation of the null
expectation for the metric for that timeseries. We used these values to
calculate SES using the following formula:
$SES = [F_{obs} - mean_{(F_{null})}]/SD_{(F_{null})}$. Unless otherwise
specified, functional diversity results are reported for standardized
values for the rest of the paper.

#### *Analysis*

*Overall Trends*

We estimated overall trends for each diversity metric using a Linear
Mixed Effects model with a random slope and intercept for each
timeseries nested within study. Differences in trends by taxa, biome,
and realm were also modeled individually as covariates in models of the
same structure.

*Study-level Trends*

We obtained study-level estimates of temporal change from the Best
Linear Unbiased Predictors (BLUP's) for each overall trend model and
assessed them in two ways. First, we looked at pairwise relationships
between all metrics to assess what kinds of community shifts are
commonly found together. We obtained correlations and bootstrapped
p-values using *corr.test* and *corCI* functions in the *psych* R
package (citation). Second, we assessed the relationship between all
metrics simultaneously by performing a cluster analysis which grouped
each study based on their similarities across all metrics. We used a
hierarchical clustering algorithm through the function *hclust* from the
R package *stats.* We included all standardized functional diversity
metrics, species richness, and Jaccard similarity in the analysis. We
report a qualitative interpretation of the groups from the cluster
analysis.

<!-- why do some studies not have blup estimates for FRic?-->

### Results

We found no significant temporal trend in species richness or functional
diversity metrics for either observed or standardized metrics. There
continued to be no trend for studies broken down by taxa, biome or
realm. We did find a significant overall decrease in Jaccard similarity,
indicating increasing turnover through time.

At the study level, the majority of studies (78%) experienced a
significant temporal change in species richness and all functional
diversity metrics. 92% of sites experienced a significant trend for
species richness, 88% for functional functional richness, 96% for
functional divergence, 88% for functional evenness, and 35% for Jaccard
similarity. Only four studies experienced no significant trend in
species richness and were also characterized by significantly decreasing
functional evenness. There was only one significant pairwise correlation
between the metrics, a positive relationship between Functional
Divergence and Functional Evenness, indicating that studies experiencing
an increase in Divergence frequently experience and increase in
Evenness.

Cluster analysis grouped all but a few studies into a cluster
characterized by non-siginficant or very small significant slopes for
all metrics. We identified four other clusters containing six studies
that were characterized by outlier trends in at least one of the metrics
and near-zero trends in the rest. The first contained two studies with
the most strongly decreasing evenness. The second, two studies with the
most strongly increasing functional divergence and increasing functional
richness. The third contained one study with strongly decreasing
functional divergence and richness, and the fourth strongly decreasing
species richness with increasing functional richness.

### Discussion

Our study represents the largest broad-scale multi-taxa assessment of
functional change through time, giving a first look at overall trends in
functional diversity and the range of changes happening in mammal, bird,
and amphibian communities. We found no systematic temporal change in any
measured dimension of functional diversity or species richness, even
within specific realms, biomes, or taxonomic groups. Species-based
results are consistent with other broad scale analyses of biodiversity
change through time [@dornelas2014] that found no overall trend in
species richness despite increasing turnover. While nearly all of the
studies included in our data experienced a significant increase or
decrease in species richness, they were observed in equal numbers
resulting in an overall trend not significantly different from zero.
Surprisingly, there was also no general trend in functional diversity
metrics indicating that, similar to species richness, communities are
experience a wide range of functional shifts. Non significant results
for study characteristics confirm that functional changes cannot be
explained by the taxa, realm, or climate characteristics of a given
study.

Individual studies in our dataset demonstrate the variety of species and
functional shifts that can happen concurrently in a community. Notably,
many studies did not experience increasing turnover (65%) despite having
significant change in functional dimensions.

-   very few sites experienced increasing turnover, but the ones that
    did were significant!

-   what does it me for turnover not to be increasing but the function
    of communities to be changing

-   Biological homogenization is one of the hypothesized meaningful
    forces

While species-level metrics are the only functional data available to
perform an analysis of this scale, they are unable to detect functional
shifts in communities with little to no turnover as they do not capture
intraspecific shifts.

Data limitations:

-   species-level traits

-   not a lot of changes in these systems already?

#### Add to supplement

-   breakdown of number of studies/timeseries for each taxa/realm etc
